[build]
  base = "derzhavnaya" # Директория с вашим билдом
  command = "npm bot.js" # Команда для сборки вашего проекта

[build.environment]
  NODE_VERSION = "14" # Версия Node.js, которая будет использоваться

